Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-2024, pull requests merged in 2024-05, with the labels that each got.

#14 Agrego estructuración de la arquitectura del proyecto
  frontend/.env
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/components/payments/payments.component.css
  frontend/src/app/components/payments/payments.component.html
  frontend/src/app/components/payments/payments.component.spec.ts
  frontend/src/app/components/payments/payments.component.ts
  frontend/src/app/layout/LeerEsto.txt
  frontend/src/app/pages/cart/cart.component.css
  frontend/src/app/pages/cart/cart.component.html
  frontend/src/app/pages/cart/cart.component.spec.ts
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/dashboard/dashboard.component.css
  frontend/src/app/pages/dashboard/dashboard.component.html
  frontend/src/app/pages/dashboard/dashboard.component.spec.ts
  frontend/src/app/pages/dashboard/dashboard.component.ts
  frontend/src/data/db.json
  frontend/src/favicon.ico
  frontend/src/index.html
  frontend/src/interfaces/order.ts
  frontend/src/interfaces/orders.ts
  frontend/src/interfaces/product.ts
  frontend/src/interfaces/products.ts
  frontend/src/interfaces/user.ts
  frontend/src/modules/admin-dashboard/admin-dashboard.component.css
  frontend/src/modules/admin-dashboard/admin-dashboard.component.html
  frontend/src/modules/admin-dashboard/admin-dashboard.component.spec.ts
  frontend/src/modules/admin-dashboard/admin-dashboard.component.ts
  frontend/src/modules/admin-dashboard/admin-dashboard.module.ts
  frontend/src/modules/client-dashboard/client-dashboard.component.css
  frontend/src/modules/client-dashboard/client-dashboard.component.html
  frontend/src/modules/client-dashboard/client-dashboard.component.spec.ts
  frontend/src/modules/client-dashboard/client-dashboard.component.ts
  frontend/src/modules/client-dashboard/client-dashboard.module.ts
  frontend/src/services/api-service.service.spec.ts
  frontend/src/services/api-service.service.ts
  frontend/src/services/product-service.service.spec.ts
  frontend/src/services/product-service.service.ts
  frontend/src/services/user-service.service.spec.ts
  frontend/src/services/user-service.service.ts
  frontend/src/styles/Leer.txt
Labels: documentation, enhancement

#16 Julieta
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/layout/header/header.component.css
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.spec.ts
  frontend/src/app/layout/header/header.component.ts
Labels: documentation, enhancement

#17 Denisse
  frontend/angular.json
  frontend/src/app/app.routes.ts
  frontend/src/app/components/contact-form/contact-form.component.css
  frontend/src/app/components/contact-form/contact-form.component.html
  frontend/src/app/components/contact-form/contact-form.component.spec.ts
  frontend/src/app/components/contact-form/contact-form.component.ts
  frontend/src/app/pages/about-us/about-us.component.css
  frontend/src/app/pages/about-us/about-us.component.html
  frontend/src/app/pages/about-us/about-us.component.spec.ts
  frontend/src/app/pages/about-us/about-us.component.ts
Labels: documentation, enhancement

#19 Gustavo
  Backend/Tienda_Campeones/.gitignore
  Backend/campeones_del_mundo.sql
Labels: documentation, enhancement

#28 Cristian
  frontend/src/app/pages/not-found/not-found.component.css
  frontend/src/app/pages/not-found/not-found.component.html
  frontend/src/app/pages/not-found/not-found.component.spec.ts
  frontend/src/app/pages/not-found/not-found.component.ts
  frontend/src/data/db.json
  frontend/src/interfaces/options.ts
  frontend/src/interfaces/order.ts
  frontend/src/interfaces/orders.ts
  frontend/src/interfaces/product.ts
  frontend/src/interfaces/products.ts
  frontend/src/interfaces/user.ts
  frontend/src/interfaces/users.ts
  frontend/src/services/api-service.service.ts
  frontend/src/services/orders.service.spec.ts
  frontend/src/services/orders.service.ts
  frontend/src/services/product-service.service.spec.ts
  frontend/src/services/product-service.service.ts
  frontend/src/services/products.service.spec.ts
  frontend/src/services/products.service.ts
  frontend/src/services/user-service.service.ts
  frontend/src/services/users.service.spec.ts
  frontend/src/services/users.service.ts
Labels: documentation, enhancement

#26 Agrego validaciones al formulario reactivo de confirmación de compra
  frontend/src/app/components/cart-resume/cart-resume.component.css
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
Labels: documentation, enhancement

#30 Victoria
  estuctura.pdf
  frontend/src/app/app.component.css
  frontend/src/app/app.component.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/components/carousel/carousel.component.css
  frontend/src/app/components/carousel/carousel.component.html
  frontend/src/app/components/carousel/carousel.component.spec.ts
  frontend/src/app/components/carousel/carousel.component.ts
  frontend/src/app/components/landing-card/landing-card.component.css
  frontend/src/app/components/landing-card/landing-card.component.html
  frontend/src/app/components/landing-card/landing-card.component.spec.ts
  frontend/src/app/components/landing-card/landing-card.component.ts
  frontend/src/app/pages/landing/landing.component.css
  frontend/src/app/pages/landing/landing.component.html
  frontend/src/app/pages/landing/landing.component.spec.ts
  frontend/src/app/pages/landing/landing.component.ts
Labels: documentation, enhancement

#31 reduzco estilos
  frontend/src/app/components/carousel/carousel.component.css
  frontend/src/app/components/landing-card/landing-card.component.css
  frontend/src/app/pages/landing/landing.component.css
Labels: Improvement

#32 update section and article
  frontend/src/app/components/landing-card/landing-card.component.html
  frontend/src/app/pages/landing/landing.component.html
Labels: Improvement

#33 Cristian
  frontend/src/app/app.routes.ts
  frontend/src/app/components/login-form/login-form.component.css
  frontend/src/app/components/login-form/login-form.component.html
  frontend/src/app/components/login-form/login-form.component.spec.ts
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/components/logout-modal/logout-modal.component.css
  frontend/src/app/components/logout-modal/logout-modal.component.html
  frontend/src/app/components/logout-modal/logout-modal.component.spec.ts
  frontend/src/app/components/logout-modal/logout-modal.component.ts
  frontend/src/app/components/register-form/register-form.component.css
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.spec.ts
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/components/theme-button/theme-button.component.html
  frontend/src/app/layout/LeerEsto.txt
  frontend/src/app/layout/header/header.component.css
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
Labels: documentation, enhancement

#36 enlace
  frontend/src/app/components/carousel/carousel.component.html
Labels: Improvement

#37 Compinet corregido
  frontend/src/app/pages/products/products.component.ts
Labels: Improvement

#38 soluciono conflictos
  frontend/src/app/app.component.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/pages/not-found/not-found.component.ts
Labels: Improvement

#39 Update de enlaces de botones e imagenes , actualizo css
  frontend/src/app/app.component.css
  frontend/src/app/components/carousel/carousel.component.ts
  frontend/src/app/components/landing-card/landing-card.component.html
  frontend/src/app/components/landing-card/landing-card.component.ts
  frontend/src/app/pages/landing/landing.component.html
  frontend/src/app/pages/landing/landing.component.ts
  frontend/src/app/pages/products/products.component.html
  frontend/src/assets/images/products/Italia/34italia.svg
  frontend/src/styles.css
Labels: Improvement

#34 agrego diseño para pagina error 404 not found
  frontend/src/app/pages/not-found/not-found.component.css
  frontend/src/app/pages/not-found/not-found.component.html
  frontend/src/assets/images/not-found/404 not found.png
Labels: documentation, enhancement

#41 Pablo
  frontend/src/app/app.component.html
  frontend/src/app/app.component.ts
  frontend/src/app/app.routes.ts
  frontend/src/app/layout/footer/footer.component.css
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/footer/footer.component.spec.ts
  frontend/src/app/layout/footer/footer.component.ts
  package-lock.json
Labels: documentation, enhancement

#42 Lautaro pena
  frontend/src/app/components/cart-item/cart-item.component.css
  frontend/src/app/components/cart-item/cart-item.component.html
  frontend/src/app/components/orders-summary/orders-summary.component.css
  frontend/src/app/components/orders-summary/orders-summary.component.html
  frontend/src/app/components/products-suggest/products-suggest.component.css
  frontend/src/app/components/products-suggest/products-suggest.component.html
  frontend/src/app/components/products-suggest/products-suggest.component.ts
  frontend/src/app/components/products-summary/products-summary.component.css
  frontend/src/app/components/products-summary/products-summary.component.html
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/pages/about-us/about-us.component.html
  frontend/src/app/pages/dashboard/dashboard.component.html
Labels: documentation, enhancement

#44 se redirecciona a 404
  frontend/src/app/components/landing-card/landing-card.component.html
  package-lock.json
Labels: Improvement

#60 Pablo - agrego item de contacto en el footer
  frontend/src/app/layout/footer/footer.component.html
Labels: documentation, enhancement

#61 Lautaro pena
  frontend/src/app/pages/products/products.component.html
  frontend/src/index.html
Labels: documentation, enhancement

#62 Cristian
  frontend/src/app/components/landing-card/landing-card.component.html
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/pages/dashboard/dashboard.component.html
  frontend/src/app/pages/not-found/not-found.component.html
Labels: documentation, enhancement

#85 Reestructuración y ajustes
  frontend/src/app/components/dashboard-table/dashboard-table.component.css
  frontend/src/app/components/dashboard-table/dashboard-table.component.html
  frontend/src/app/components/dashboard-table/dashboard-table.component.spec.ts
  frontend/src/app/components/dashboard-table/dashboard-table.component.ts
  frontend/src/app/components/management/management.component.css
  frontend/src/app/components/management/management.component.html
  frontend/src/app/components/management/management.component.spec.ts
  frontend/src/app/components/management/management.component.ts
  frontend/src/app/components/order-management/order-management.component.css
  frontend/src/app/components/order-management/order-management.component.html
  frontend/src/app/components/order-management/order-management.component.spec.ts
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/components/product-management/product-management.component.css
  frontend/src/app/components/product-management/product-management.component.html
  frontend/src/app/components/product-management/product-management.component.spec.ts
  frontend/src/app/components/product-management/product-management.component.ts
  frontend/src/app/components/products-summary/products-summary.component.css
  frontend/src/app/components/products-summary/products-summary.component.html
  frontend/src/app/components/products-summary/products-summary.component.ts
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/app/pages/dashboard/dashboard.component.ts
Labels: documentation, Fixing

#86 Fix de estructura de componentes en dashboard
  frontend/src/app/components/dashboard-table/dashboard-table.component.css
  frontend/src/app/components/dashboard-table/dashboard-table.component.html
  frontend/src/app/components/dashboard-table/dashboard-table.component.spec.ts
  frontend/src/app/components/dashboard-table/dashboard-table.component.ts
  frontend/src/app/components/management/management.component.css
  frontend/src/app/components/management/management.component.html
  frontend/src/app/components/management/management.component.spec.ts
  frontend/src/app/components/management/management.component.ts
  frontend/src/app/components/order-management/order-management.component.css
  frontend/src/app/components/order-management/order-management.component.html
  frontend/src/app/components/order-management/order-management.component.spec.ts
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/components/product-management/product-management.component.css
  frontend/src/app/components/product-management/product-management.component.html
  frontend/src/app/components/product-management/product-management.component.spec.ts
  frontend/src/app/components/product-management/product-management.component.ts
  frontend/src/app/components/products-summary/products-summary.component.css
  frontend/src/app/components/products-summary/products-summary.component.html
  frontend/src/app/components/products-summary/products-summary.component.ts
  frontend/src/app/layout/footer/footer.component.html
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.html
  frontend/src/app/pages/admin-dashboard/admin-dashboard.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/app/pages/dashboard/dashboard.component.ts
Labels: documentation, Fixing

#87 Hago fix de servicios
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  estuctura.pdf
  frontend/src/app/app.config.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/app/pages/products/products.component.ts
  frontend/src/index.html
  frontend/src/interfaces/product.ts
  frontend/src/services/api.service.spec.ts
  frontend/src/services/api.service.ts
  frontend/src/services/orders.service.ts
  frontend/src/services/products.service.ts
Labels: documentation, enhancement

#88 Form Reactivo e implementación del registro de usuario.
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/contact-form/contact-form.component.html
  frontend/src/app/components/register-form/register-form.component.css
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
  frontend/src/app/pages/about-us/about-us.component.html
  frontend/src/app/services/auth.service.spec.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/app/services/modalstatus.service.spec.ts
  frontend/src/app/services/modalstatus.service.ts
  frontend/src/interfaces/user.ts
Labels: documentation, enhancement

#121 Cristian
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  frontend/src/app/components/card-product/card-product.component.css
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.spec.ts
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-item/cart-item.component.css
  frontend/src/app/components/cart-item/cart-item.component.html
  frontend/src/app/components/cart-item/cart-item.component.ts
  frontend/src/app/components/cart-list/cart-list.component.html
  frontend/src/app/components/cart-list/cart-list.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/pages/cart/cart.component.html
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/products/products.component.html
  frontend/src/app/pages/products/products.component.ts
  frontend/src/interfaces/cartList.ts
  frontend/src/interfaces/order.ts
  frontend/src/interfaces/param-config.ts
  frontend/src/interfaces/payment.ts
  frontend/src/interfaces/product.ts
  frontend/src/interfaces/products.ts
  frontend/src/interfaces/user.ts
  frontend/src/pipes/price.pipe.spec.ts
  frontend/src/pipes/price.pipe.ts
  frontend/src/pipes/truncate-name.pipe.spec.ts
  frontend/src/pipes/truncate-name.pipe.ts
  frontend/src/services/api.service.ts
  frontend/src/services/payment.service.spec.ts
  frontend/src/services/payment.service.ts
  frontend/src/services/products.service.ts
  frontend/src/services/users.service.ts
  frontend/src/styles/Leer.txt
Labels: documentation, enhancement

#122 Cambios en el form de registro y en el guard.
  frontend/src/app/app.routes.ts
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/guards/auth.guard.spec.ts
  frontend/src/app/guards/auth.guard.ts
  frontend/src/app/services/auth.service.ts
Labels: documentation, enhancement

#124 Cambios en el formulario de registro
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.ts
Labels: documentation, enhancement

#125 Cristian
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-item/cart-item.component.html
  frontend/src/app/components/cart-item/cart-item.component.ts
  frontend/src/app/components/cart-list/cart-list.component.html
  frontend/src/app/components/cart-list/cart-list.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/pages/cart/cart.component.html
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/products/products.component.html
  frontend/src/app/pages/products/products.component.ts
  frontend/src/interfaces/product.ts
  frontend/src/services/orders.service.ts
  frontend/src/services/products.service.spec.ts
  frontend/src/services/products.service.ts
Labels: documentation

#129 Gustavo
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  Backend/Tienda_Campeones/users/__init__.py
  Backend/Tienda_Campeones/users/admin.py
  Backend/Tienda_Campeones/users/apps.py
  Backend/Tienda_Campeones/users/migrations/0001_initial.py
  Backend/Tienda_Campeones/users/migrations/__init__.py
  Backend/Tienda_Campeones/users/models.py
  Backend/Tienda_Campeones/users/tests.py
  Backend/Tienda_Campeones/users/views.py
  Backend/Tienda_Campeones/web/Serializers/productos_serializers.py
  Backend/Tienda_Campeones/web/admin.py
  Backend/Tienda_Campeones/web/migrations/0001_initial.py
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  Backend/Tienda_Campeones/web/models.py
Labels: documentation, enhancement
