Repository Proyecto-integrador-ISPC-2024/proyecto-integrador-2024, pull requests merged in 2024-06, with the labels that each got.

#130 finalizacion del desarrollo de productos
  Backend/Tienda_Campeones/.vscode/settings.json
  Backend/Tienda_Campeones/Tienda_Campeones/urls.py
  Backend/Tienda_Campeones/web/Serializers/pedidos_serializers.py
  Backend/Tienda_Campeones/web/Serializers/productos_serializers.py
  Backend/Tienda_Campeones/web/migrations/0002_alter_productostalles_productos.py
  Backend/Tienda_Campeones/web/migrations/0003_rename_productos_productostalles_id_producto_and_more.py
  Backend/Tienda_Campeones/web/migrations/0004_alter_productostalles_id_producto.py
  Backend/Tienda_Campeones/web/models.py
  Backend/Tienda_Campeones/web/routers.py
  Backend/Tienda_Campeones/web/views.py
Labels: documentation, enhancement

#131 arreglo en producto serializers
  Backend/Tienda_Campeones/Tienda_Campeones/urls.py
  Backend/Tienda_Campeones/web/Serializers/productos_serializers.py
  Backend/Tienda_Campeones/web/migrations/0005_rename_pedidos_detallespedido_id_pedido_and_more.py
  Backend/Tienda_Campeones/web/models.py
  Backend/Tienda_Campeones/web/routers.py
  Backend/Tienda_Campeones/web/views/pedidoViews.py
  Backend/Tienda_Campeones/web/views/productoViews.py
Labels: Fixing

#133 agregando interceptor para autenticación futura basada en JWT
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/guards/auth.guard.ts
  frontend/src/app/interceptor/auth-interceptor.interceptor.spec.ts
  frontend/src/app/interceptor/auth-interceptor.interceptor.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/interfaces/user.ts
Labels: documentation, enhancement

#136 Julieta
  frontend/src/app/pages/products/products.component.html
  frontend/src/app/pages/products/products.component.ts
  frontend/src/services/products.service.ts
Labels: documentation, enhancement

#137 Jesica
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/spinner/spinner.component.ts
  frontend/src/app/pages/products/products.component.html
Labels: documentation, enhancement

#140 Cristian
  frontend/src/app/app.component.html
  frontend/src/app/app.routes.ts
  frontend/src/app/components/cart-item/cart-item.component.html
  frontend/src/app/components/cart-item/cart-item.component.ts
  frontend/src/app/components/cart-list/cart-list.component.html
  frontend/src/app/components/cart-list/cart-list.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/payments/payments.component.html
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/pages/cart/cart.component.html
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/products/products.component.css
  frontend/src/app/pages/products/products.component.html
  frontend/src/assets/images/payments/naranjax.webp
  frontend/src/assets/images/payments/paypal.webp
  frontend/src/interfaces/order.ts
  frontend/src/interfaces/product.ts
  frontend/src/interfaces/user.ts
  frontend/src/services/api.service.ts
  frontend/src/services/cart.service.spec.ts
  frontend/src/services/cart.service.ts
  frontend/src/services/users.service.ts
Labels: documentation, enhancement

#141 Victoria
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  frontend/src/app/components/login-form/login-form.component.html
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/components/logout-modal/logout-modal.component.html
  frontend/src/app/components/logout-modal/logout-modal.component.ts
Labels: documentation, enhancement

#143 Subo los archivos correspondientes al dashboard client con método para cancelar pedido, peticiones get y métodos para renderizar las tablas
  frontend/src/app/components/orders-summary/orders-summary.component.html
  frontend/src/app/components/orders-summary/orders-summary.component.ts
  frontend/src/app/components/products-suggest/products-suggest.component.css
  frontend/src/app/components/products-suggest/products-suggest.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/services/orders.service.ts
Labels: enhancement

#144 Pablo
  frontend/src/app/components/order-management/order-management.component.html
  frontend/src/app/components/order-management/order-management.component.ts
Labels: documentation, enhancement

#135 Agregado view y serializers de users
  Backend/Der.drawio.png
  Backend/DiagramaClases.drawio.pdf
  Backend/DiagramaClases.png
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  Backend/Tienda_Campeones/Tienda_Campeones/urls.py
  Backend/Tienda_Campeones/users/usuarioapi/__init__.py
  Backend/Tienda_Campeones/users/usuarioapi/api.py
  Backend/Tienda_Campeones/users/usuarioapi/routers.py
  Backend/Tienda_Campeones/users/usuarioapi/usuario_serializers.py
  Backend/Tienda_Campeones/users/views.py
Labels: documentation, enhancement

#145 Subo corrección con la interface en los archivos y agrego en orders.service.ts el puerto pedidos.
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/components/orders-summary/orders-summary.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/services/orders.service.ts
Labels: documentation, enhancement

#147 Cristian
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/interfaces/options.ts
  frontend/src/interfaces/order.ts
  frontend/src/interfaces/orders.ts
  frontend/src/interfaces/param-config.ts
  frontend/src/interfaces/payment.ts
  frontend/src/interfaces/products.ts
  frontend/src/interfaces/users.ts
  frontend/src/pipes/price.pipe.spec.ts
  frontend/src/pipes/price.pipe.ts
  frontend/src/pipes/truncate-name.pipe.spec.ts
  frontend/src/pipes/truncate-name.pipe.ts
  frontend/src/services/orders.service.ts
Labels: documentation, enhancement

#148 Agrego estilos en order management
  frontend/src/app/components/order-management/order-management.component.css
Labels: documentation, enhancement

#149 Agrego documento README.md
  README.md
Labels: documentation, enhancement

#150 Reestructuro manipulación de datos que se reciben desde backend
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/interfaces/product.ts
  frontend/src/services/cart.service.ts
Labels: documentation, Fixing

#151 Fix de errores
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/interfaces/product.ts
  frontend/src/services/cart.service.ts
Labels: documentation, Fixing

#154 Cristian
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/products/products.component.ts
  frontend/src/interfaces/cartOrder.ts
  frontend/src/interfaces/paymentMethodData.ts
  frontend/src/interfaces/product.ts
  frontend/src/services/api.service.ts
  frontend/src/services/cart.service.ts
  frontend/src/services/products.service.ts
Labels: documentation, enhancement

#155 Denisse
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/guards/auth.guard.ts
  frontend/src/app/layout/header/header.component.css
  frontend/src/app/services/auth.service.ts
  frontend/src/interfaces/user.ts
Labels: documentation, enhancement

#158 Victoria
  frontend/src/app/components/login-form/login-form.component.html
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/interceptor/auth-interceptor.interceptor.spec.ts
  frontend/src/app/services/auth.service.ts
Labels: documentation, enhancement

#160 Cristian
  frontend/src/app/layout/header/header.component.css
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
Labels: documentation, enhancement

#163 solucionado importación de interceptor en providers
  frontend/src/app/app.config.ts
Labels: documentation, enhancement

#164 Subo los cambios en el dashboard
  frontend/src/app/components/order-management/order-management.component.css
  frontend/src/app/components/order-management/order-management.component.html
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/components/orders-summary/orders-summary.component.css
  frontend/src/app/components/orders-summary/orders-summary.component.html
  frontend/src/app/components/orders-summary/orders-summary.component.ts
  frontend/src/app/components/products-suggest/products-suggest.component.css
  frontend/src/app/components/products-suggest/products-suggest.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/interfaces/order.ts
  frontend/src/services/api.service.ts
  frontend/src/services/orders.service.ts
Labels: documentation, enhancement

#165 Arreglando urls y peticiones del login
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/services/auth.service.ts
Labels: documentation, enhancement

#166 Modifico el constructor del client dashboard
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
Labels: documentation, enhancement

#167 Fix de autenticación en rutas protegidas y ajustes en api service
  frontend/src/app/app.config.ts
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/interceptor/auth-interceptor.interceptor.ts
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/dashboard/dashboard.component.html
  frontend/src/app/services/auth.service.ts
  frontend/src/services/api.service.ts
Labels: documentation, Fixing

#168 Agrego cambios en el api service y orders service
  frontend/src/services/api.service.ts
  frontend/src/services/orders.service.ts
Labels: documentation, enhancement

#170 Gustavo
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
Labels: enhancement, Fixing

#171 Cristian
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/pages/products/products.component.ts
  frontend/src/interfaces/user.ts
  frontend/src/services/cart.service.ts
  frontend/src/services/users.service.spec.ts
  frontend/src/services/users.service.ts
Labels: documentation, Fixing

#172 Cristian
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/pages/cart/cart.component.html
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/app/services/v.txt
Labels: documentation, enhancement, Fixing

#173 Merge para realizar release de proyecto
  Backend/Base_Campeones.sql
  Backend/Tienda_Campeones/Tienda_Campeones/settings.py
  Backend/Tienda_Campeones/Tienda_Campeones/urls.py
  Backend/Tienda_Campeones/users/routers.py
  Backend/Tienda_Campeones/users/usuarioapi/api.py
  Backend/Tienda_Campeones/users/usuarioapi/routers.py
  Backend/Tienda_Campeones/users/usuarioapi/usuario_serializers.py
  Backend/Tienda_Campeones/users/views.py
  Backend/Tienda_Campeones/web/Serializers/pedidos_serializers.py
  Backend/Tienda_Campeones/web/Serializers/productos_serializers.py
  Backend/Tienda_Campeones/web/migrations/__pycache__/__init__.cpython-311.pyc
  Backend/Tienda_Campeones/web/routers.py
  Backend/Tienda_Campeones/web/views/pedidoViews.py
  Backend/Tienda_Campeones/web/views/productoViews.py
  frontend/src/app/app.config.ts
  frontend/src/app/components/card-product/card-product.component.html
  frontend/src/app/components/card-product/card-product.component.ts
  frontend/src/app/components/cart-resume/cart-resume.component.html
  frontend/src/app/components/cart-resume/cart-resume.component.ts
  frontend/src/app/components/login-form/login-form.component.html
  frontend/src/app/components/login-form/login-form.component.ts
  frontend/src/app/components/order-management/order-management.component.css
  frontend/src/app/components/order-management/order-management.component.html
  frontend/src/app/components/order-management/order-management.component.ts
  frontend/src/app/components/orders-summary/orders-summary.component.css
  frontend/src/app/components/orders-summary/orders-summary.component.html
  frontend/src/app/components/orders-summary/orders-summary.component.ts
  frontend/src/app/components/products-suggest/products-suggest.component.css
  frontend/src/app/components/products-suggest/products-suggest.component.html
  frontend/src/app/components/register-form/register-form.component.html
  frontend/src/app/components/register-form/register-form.component.ts
  frontend/src/app/guards/auth.guard.ts
  frontend/src/app/interceptor/auth-interceptor.interceptor.spec.ts
  frontend/src/app/interceptor/auth-interceptor.interceptor.ts
  frontend/src/app/layout/header/header.component.css
  frontend/src/app/layout/header/header.component.html
  frontend/src/app/layout/header/header.component.ts
  frontend/src/app/pages/cart/cart.component.html
  frontend/src/app/pages/cart/cart.component.ts
  frontend/src/app/pages/client-dashboard/client-dashboard.component.html
  frontend/src/app/pages/client-dashboard/client-dashboard.component.ts
  frontend/src/app/pages/dashboard/dashboard.component.html
  frontend/src/app/pages/products/products.component.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/app/services/v.txt
  frontend/src/interfaces/cartOrder.ts
  frontend/src/interfaces/order.ts
  frontend/src/interfaces/paymentMethodData.ts
  frontend/src/interfaces/product.ts
  frontend/src/interfaces/user.ts
  frontend/src/services/api.service.ts
  frontend/src/services/cart.service.ts
  frontend/src/services/orders.service.ts
  frontend/src/services/products.service.ts
  frontend/src/services/users.service.spec.ts
  frontend/src/services/users.service.ts
Labels: documentation

#174 Ajusto package-lock.json según sugerencias de dependabot
  frontend/package-lock.json
Labels: documentation, Fixing
